import os
from tkinter import *
r = Tk()
r.title('create project')
r.geometry('300x100')
format_type = StringVar()
Label(r, text='write the project path').pack()
Entry(r, textvariable=format_type).pack()
def create():
    h = format_type.get()
    print(h)
    os.mkdir(f'{h}')
    os.mkdir(f'{h}\\PLC_things')
    SI = open('PLC_thingsp\\SI.py', 'r')
    SIR = open('PLC_thingsp\\SIR.py', 'r')
    SOIS = open('PLC_thingsp\\SOIS.py', 'r')
    strike_lib = open('PLC_thingsp\\strike_lib.py', 'r')
    lind = open('PLC_thingsp\\license.txt', 'r')
    lin = open('license.txt','r')
    mai = open('cvr.py','r')
    sapfl = open('SAPFL.py','r')
    mSI = open(f'{h}\\PLC_things\\SI.py', 'x')
    mSIR = open(f'{h}\\PLC_things\\SIR.py', 'x')
    mSOIS = open(f'{h}\\PLC_things\\SOIS.py', 'x')
    mstrike_lib = open(f'{h}\\PLC_things\\strike_lib.py', 'x')
    mmai = open(f'{h}\\cvr.py','x')
    mlin = open(f'{h}\\license.txt', 'x')
    mlind = open(f'{h}\\PLC_things\\license.txt', 'x')
    msapfl = open(f'{h}\\SAPFL.py', 'x')
    mSI.write(SI.read())
    mSIR.write(SIR.read())
    mSOIS.write(SOIS.read())
    mstrike_lib.write(strike_lib.read())
    mSOIS.write(SOIS.read())
    mmai.write(mai.read())
    mlin.write(lin.read())
    mlind.write(lind.read())
    msapfl.write(sapfl.read())
    SI.close()
    mSI.close()
    SIR.close()
    mSIR.close()
    SOIS.close()
    mSOIS.close()
    strike_lib.close()
    mstrike_lib.close()
    lind.close()
    lin.close()
    mai.close()
    sapfl.close()
    mmai.close()
    msapfl.close()
    mlin.close()
    mlind.close()
    os.rename(f'{h}\\cvr.py',f'{h}\\main.py')
Button(r,text='create it',command=create).pack()
r.mainloop()